### ISSUE TITLE
Typescript definitions, optionals

### ISSUE THREAD

**Issue by Jojoshua** [andrelmlins/svelte-grid-responsive#15]
If using typescript, the demo example code won't work right. All of the properties on interface GridProps are required. I am thinking only a couple should be required and all else should be marked as optional.

**Comment by andrelmlins** [comment]
Hi, I'm checking the reason for this error and I should make a version available with the fix.

**Comment by andrelmlins** [comment]
Available in version 1.2.4

Thanks for raising this point.
