### ISSUE TITLE
is it possible to order elements

### ISSUE THREAD

**Issue by MihailsKuzmins** [andrelmlins/svelte-grid-responsive#9]
Hi, nice lib :)

bootstrap offers a way to [order elements](https://getbootstrap.com/docs/4.0/layout/grid/#order-classes) in the grid. I looked at the source code I haven't found this functionality. Maybe I overlooked it. So it is possible to order elements?

If no would it be possible to add this functionality to the lib?

**Comment by andrelmlins** [comment]
Hi @MihailsKuzmins ,

Thanks for the suggestion, we don't support ordering at the moment. But I will add this functionality.

**Comment by andrelmlins** [comment]
Available in version 1.1.0
Commit: https://github.com/andrelmlins/svelte-grid-responsive/commit/4d18b721e1515118e1b29ff798531fcccf1daa28

**Comment by andrelmlins** [comment]
Thanks again for the suggestion

**Comment by MihailsKuzmins** [comment]
@andrelmlins, oh nice. Thank you very much
I do look forward to seeing the new functionality in action
